const PathConstants = {
  HOME: "/",
  SIGN_IN: "/signin",
  SIGN_UP: "/signup",
  LOCK: "/lock",
  CHECKOUT: "sales/checkout",
  RECEIPTS: "sales/receipts",
  REFUND: "sales/refund",
  ADD_CUSTOMER: "customers/add-customer",
  CUSTOMER_LIST: "customers/customer-list",
  PURCHASE_HISTORY: "customers/purchase-history",
  EDIT_CUSTOMER: "customers/edit-customer",
  ADD_EMPLOYEE: "employees/add-employee",
  EMPLOYEE_LIST: "employees/employee-list",
  EDIT_EMPLOYEE: "employees/edit-employee",
  LOYALTY_PROGRAMS: "loyalty/loyalty-programs",
  ADD_LOYALTY_PROGRAM: "loyalty/add-loyalty-program",
  EDIT_LOYALTY_PROGRAM: "loyalty/edit-loyalty-program",
  TIMECARDS: "employees/timecards",
  ADD_TIMECARD: "employees/add-timecard",
};
export default PathConstants;
